thenativeweb/wolkenkit

- lib/bin/wolkenkit.js
- test/stories/helpers/getWolkenkit.js
- test/stories/setupTests.js
Hi @grundhoeferj!
I have added the missing `--version` flag, but I have not been able to run the AWS tests (because I was on train, and the wi-fi was quite unstable).
So, could you please have a look at my changes, and check whether the AWS tests work? If everything is fine, can you then please merge this PR? If not, can you please comment on what was not okay?
Thanks 😊
> Add version flag. Closes thenativeweb/org#473

- configuration/1.0.0/broker/container.js
- configuration/1.0.0/core/container.js
- configuration/1.0.0/depot-file/container.js
- configuration/1.0.0/flows/container.js
- configuration/1.0.0/node-modules/container.js
- configuration/1.0.0/schema.js
- configuration/1.0.1/broker/container.js
- configuration/1.0.1/core/container.js
- configuration/1.0.1/depot-file/container.js
- configuration/1.0.1/flows/container.js
- configuration/1.0.1/node-modules/container.js
- configuration/1.0.1/schema.js
- configuration/1.1.0/broker/container.js
- configuration/1.1.0/core/container.js
- configuration/1.1.0/depot-file/container.js
- configuration/1.1.0/flows/container.js
- configuration/1.1.0/node-modules/container.js
- configuration/1.1.0/schema.js
- configuration/latest/broker/container.js
- configuration/latest/core/container.js
- configuration/latest/depot-file/container.js
- configuration/latest/flows/container.js
- configuration/latest/node-modules/container.js
- configuration/latest/schema.js
- package-lock.json
- test/units/application/getConfigurationTests.js
- test/units/network/getIpAddressesTests.js
Hi @grundhoeferj!
While testing the new CLI, @revrng has discovered a bug: In the `wolkenkit` section of an application's `package.json` file, the property `node/environment` was mandatory (but should be optional).
I have fixed this, adjusted the tests, and verified that everything still works on AWS.
Could you please have a look at this PR, and squash/merge this, if you are fine with it?
> Make node environment optional. Closes thenativeweb/org#478

- lib/docker/ensureNetworkExists.js
- lib/docker/getContainers.js
- lib/docker/ping.js
Since on windows the argument `--format` expect double quotes , we have to change this. Notice: double quotes also works on unix systems.
> Fix docker commands for windows.

- lib/certificate/index.js
- lib/certificate/isNameMatching.js
- lib/wolkenkit/commands/health/checkCertificate.js
- test/stories/shared/applicationLifecycleTests.js
- test/units/certificate/isNameMatchingTests.js
I have fixed thenativeweb/org#491 … could you please review it, and squash/merge it if you are fine with it?
The AWS tests run fine, and I have also adjusted the unit tests, they are green, too.
> Make certificate matching pay attention to wildcards. Closes thenativeweb/org#491

- README.md
- package-lock.json
- package.json
- src/telemetry/index.js
- src/wolkenkit/commands/encrypt/index.js
- src/wolkenkit/commands/shared/attachDebugger.js
- src/wolkenkit/commands/shared/startOpensshTunnel.js
- src/wolkenkit/commands/shared/startPuttyTunnel.js
- src/wolkenkit/commands/shared/startTunnel.js
- src/wolkenkit/commands/shared/waitForApplication.js
- src/wolkenkit/commands/shared/waitForSshTunnel.js
- test/stories/helpers/setupAws.js
- test/stories/terraform/setup-local.sh
- test/stories/terraform/setup-remote.sh
This morning, I was up early, and I removed `request` and `requestretry`, and instead added `axios` and `async-retry`.
Besides, I also changed that we no longer wait for the `/ping` route, but now just for root, as this is the endpoint you can also access in the browser.
Please do *NOT YET*  merge this, as we still need to run the tests and check backwards compatibility, but what I wanted you to ask was if you could just review it, especially the cases that are related to aufwind, if I missed anything.
Thanks 😊
> Introduce axios and ping root.

- package.json
- src/wolkenkit/commands/shared/validateCode.js
@mattwagl mentioned in #122 that we use an outdated language spec to validate the code of wolkenkit applications, and I've updated the responsible line of code.
Could you please have a look at this, and squash / merge it, if you are fine with this?
> Support object rest operator when linting code. Close #122

- package-lock.json
- package.json
- src/bin/wolkenkit.js
- src/cli/commands/register.js
Hi @mattwagl 😊 
I have changed the error output so that the CLI now always shows the verbose information with the error details, no matter whether verbose mode was enabled or not. This should solve #135, and improve usability.
Can you please have a look at it, and if you are happy with it, squash and merge it?
I have already run all the tests (even the ones on AWS), and everything works so far 😊
> Improve error output when a CLI command fails. Closes #135

- lib/common/data/PriorityQueue/GetPriority.ts
- lib/common/data/PriorityQueue/IsEqual.ts
- lib/common/data/PriorityQueue/PriorityQueue.ts
- lib/common/data/PriorityQueue/index.ts
- test/unit/common/data/PriorityQueueTests.ts
Hi @yeldiRium 👋 
As announced on Slack, I have found the time to implement a first draft of an in-memory priority queue this weekend.
There's still room for improvement (e.g., a lookup index for efficiently accessing individual elements is missing), and also I'm not perfectly sure about the API, but the basic implementation seems to work, and it is tested 😊 
Could you please have a look at it, and decide, whether you already would like to squash / merge it, or if we should take further steps first before doing this? If you decide to squash / merge, feel free to do so 😊
> Implement in-memory priority queue.

- lib/common/utils/network/getAvailablePort.ts
- lib/common/utils/network/getAvailablePorts.ts
- test/runtime/microservice/processes/command/processTests.ts
- test/runtime/microservice/processes/dispatcher/processTests.js
- test/runtime/microservice/processes/domainEvent/processTests.ts
- test/unit/common/utils/network/getAvailablePortsTests.ts
Although I had introduced the timeout in getting an available port, the tests still crashed from time to time, so I took some time to dive into this.
Found out that we had a race condition in one of the runtime tests, where we asked for two ports in sequence, without using them. So sometimes, the second was just the same as the first, and hence the tests crashed.
I have now changed the tests, and introduced a `getAvailablePorts` function which returns a number of available ports, in addition to the `getAvailablePort` function which returns only a single one.
If you are fine with this, could you please squash / merge this?
> Fix get ports.

- test/integration/post.ts
- test/integration/pre.ts
Hi @yeldiRium 😊 
If pre and / or post of the integration tests failed, it didn't exit with an exit code 1. This has been fixed.
If you are fine with this, can you please squash / merge this?
> Make pre and post fail on error.

- .dependabot/config.yml
In #305 I removed @mattwagl from the code owners file, since he mentioned that right now he would prefer if you and me merged PRs for wolkenkit. In consequence it doesn't make sense that Dependabot PRs get assigned to him, since he is not allowed to merge them anyway.
So to avoid that he gets lots of mails he does not need to care about, I removed him from the Dependabot configuration for now.
Can you please review, squash and merge?
> Remove @mattwagl from Dependabot configuration.

- lib/stores/priorityQueueStore/createPriorityQueueStore.ts
Hi @goloroden,
as further preparation for #339 I've added a helper function to easier create a `PriorityQueueStore` instance, mirroring the approach used for the `DomainEventStore`.
Feel free to merge it, if you're fine with it.
> Add helper to create a PriorityQueueStore instance.

- lib/stores/priorityQueueStore/InMemory/InMemoryPriorityQueueStore.ts
- lib/stores/priorityQueueStore/ItemIdentifier.ts
- lib/stores/priorityQueueStore/PriorityQueueStore.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
Hi @goloroden,
as in #339 discussed, I've rewritten the interface of the `PriorityQueueStore` to accept only the identifiers of the relevant items.
To help with that I've added the `ItemIdentifier` interface and placed it in the `priorityQueueStore` folder, since it is not relevant to the rest of the project so far.
Please take a look and feel free to merge, if all is well.
> Rewrite priority queue store interface.

- lib/apis/middlewares/streamNdjson.ts
- lib/apis/observeDomainEvents/http/index.ts
- lib/apis/observeDomainEvents/http/v2/getDomainEvents.ts
- test/shared/http/asJsonStream.ts
- test/unit/apis/middlewares/streamNdjsonTests.ts
- test/unit/apis/observeDomainEvents/httpTests.ts
Hi @goloroden,
as discussed in #339 I've extracted a middleware from the `observeDomainEvents` api that sets up a connection as using `application/x-ndjson` and sends a heartbeat.
I've added tests for the middleware and had to make slight changes to the helper `WriteStream` `asJsonStream` which luckily don't affect the other places in which the helper is used.
Feel free to merge the changes if everything is well.
> Extract streamNdjson middleware and use it in observeDomainEvents api.

- test/shared/http/runAsServer.ts
- test/unit/apis/middlewares/streamNdjsonTests.ts
As announced on Slack earlier this day, I've tried to create a replacement for `supertest`, based on `axios`. It was actually way easier than I thought, and to prove that things work I have changed the tests for the NDJSON middleware to the new component.
I have not yet replaced it everywhere, and hence I have not yet removed the dependency to `supertest`. I first wanted to get some feedback from your side.
What do you think on this approach?
(It actually solves the issues we had with the tests, since `axios` has a way better interface than `superagent` when dealing with streams.)
> Replace supertest by custom implementation.

- lib/runtimes/microservice/processes/dispatcher/Configuration.ts
- lib/runtimes/microservice/processes/dispatcher/app.ts
- lib/runtimes/microservice/processes/dispatcher/getApi.ts
- lib/runtimes/microservice/processes/dispatcher/getConfiguration.ts
- lib/runtimes/microservice/processes/dispatcher/getOnReceiveCommand.ts
- lib/stores/priorityQueueStore/createPriorityQueueStore.ts
- package-lock.json
- test/runtime/microservice/processes/dispatcher/processTests.ts
This is a draft based on #355.
It contains an implementation of the `dispatcher` process for the `microservices` runtime. If #355 in its current form at time of writing this PR will be merged, this can be merged directly after it (although due to the squash&merge approach a rebase will probably be necessary).
This implementation is built with the current polling concept in #355 in mind. If #358 were to be continued and merged before this PR, it would need a rewrite. But I suggest we merge this after #355 is done and then base #358 on this PR's content.
> Implement dispatcher process for microservice runtime.

- lib/common/domain/handleCommand.ts
- test/shared/applications/javascript/base/build/domain/sampleContext/sampleAggregate/commands/authorize.js
- test/unit/common/domain/handleCommandTests.ts
* Pass the state value instead of the CurrentAggregateState when calling `command#isAuthorized`.
* Alter the authorize test command to reject authorization when the state property is not found.
* Add test to verify that authorization passes with the correct state value.
This fixes a bug I encountered by adding custom authorization to an `amend` command on the sample `message` aggregate by using typescript.
The `CommandHandler` interface expects a `TState extends State` however `State` is a type redirecting to `object`.
This makes TS a bit confused with this defaulting to `object` and making the compiler accept to pass the `CurrentAggregateState<TState>` instead of the `TState` to the `isAuthorized` handler.
> Fix command handler authorization.

- templates/blank/typescript/tsconfig.json
- templates/chat-simplified/typescript/tsconfig.json
- templates/chat/typescript/tsconfig.json
- tsconfig.json
Fixes #783.
It includes now `sourcemap` files along with typescript definitions.
This allows users to step through Wolkenkit sources during debug.
The published Wolkenkit package already embeds both typescript sources (`lib`) and compiled output (`build/lib`) so no additional work than publishing a new version should be required.
> Include sourcemaps for Typescript users.

- lib/apis/awaitCommandWithMetadata/http/v2/awaitCommandWithMetadata.ts
- lib/apis/awaitCommandWithMetadata/http/v2/index.ts
- lib/apis/base/WolkenkitRequestHandler.ts
- lib/apis/base/getApiBase.ts
- lib/apis/base/streamNdjsonMiddleware.ts
- lib/apis/observeDomainEvents/http/v2/getDomainEvents.ts
- lib/apis/observeDomainEvents/http/v2/index.ts
- lib/apis/queryDomainEventStore/http/v2/getDomainEventsByCausationId.ts
- lib/apis/queryDomainEventStore/http/v2/getDomainEventsByCorrelationId.ts
- lib/apis/queryDomainEventStore/http/v2/getReplay.ts
- lib/apis/queryDomainEventStore/http/v2/getReplayForAggregate.ts
- lib/apis/subscribeMessages/http/v2/getMessages.ts
- lib/apis/subscribeMessages/http/v2/index.ts
- test/unit/apis/base/streamNdjsonTests.ts
- test/unit/apis/middlewares/streamNdjsonTests.ts
- test/unit/apis/observeDomainEvents/httpTests.ts
This closes #836.
Extends the express Request type with the new method `startStream`,
which then sends headers and status 200 and starts the heartbeat.
The middleware is now included with the base api and usage is decided
in the individual routes.
> feat: Defer stream start in ndjson middleware until call from route.

- lib/apis/handleCommand/http/v2/Client.ts
- lib/apis/handleCommand/http/v2/postCommand.ts
- test/unit/apis/handleCommand/httpTests.ts
> feat: Split handleCommand api into separate routes for commands.

- lib/clis/wolkenkit/createDeployment/dockerCompose/getMicroserviceInMemoryManifest.ts
- lib/clis/wolkenkit/createDeployment/dockerCompose/getMicroservicePostgresManifest.ts
- lib/clis/wolkenkit/createDeployment/dockerCompose/getSingleProcessInMemoryManifest.ts
- lib/clis/wolkenkit/createDeployment/dockerCompose/getSingleProcessPostgresManifest.ts
- lib/clis/wolkenkit/init/createDockerConfiguration.ts
fix: syntax errors in docker and docker compose manifests.
They don't work OOTB with docker 19.03.8 and docker-compose 1.25.5.
> Fix syntax errors in docker and docker compose manifests

- package-lock.json
- package.json
Move `streamtoarray` to dependencies.
The domain microservice needs it.
> Fix domain microservice dependencies

- lib/apis/awaitItem/http/v2/Client.ts
- lib/apis/awaitItem/http/v2/awaitItem.ts
- lib/common/domain/doesItemIdentifierWithClientMatchDomainEvent.ts
- lib/runtimes/microservice/processes/domain/Configuration.ts
- lib/runtimes/microservice/processes/domain/app.ts
- lib/runtimes/microservice/processes/domain/fetchCommand.ts
- lib/runtimes/microservice/processes/domain/getConfiguration.ts
- lib/runtimes/microservice/processes/domainEventDispatcher/Configuration.ts
- lib/runtimes/microservice/processes/domainEventDispatcher/app.ts
- lib/runtimes/microservice/processes/domainEventDispatcher/getApi.ts
- lib/runtimes/microservice/processes/domainEventDispatcher/getConfiguration.ts
- lib/runtimes/singleProcess/processes/main/Configuration.ts
- lib/runtimes/singleProcess/processes/main/app.ts
- lib/runtimes/singleProcess/processes/main/fetchCommand.ts
- lib/runtimes/singleProcess/processes/main/getConfiguration.ts
- lib/stores/priorityQueueStore/InMemory/InMemoryPriorityQueueStore.ts
- lib/stores/priorityQueueStore/LockMetadata.ts
- lib/stores/priorityQueueStore/MongoDb/MongoDbPriorityQueueStore.ts
- lib/stores/priorityQueueStore/MySql/MySqlPriorityQueueStore.ts
- lib/stores/priorityQueueStore/Postgres/PostgresPriorityQueueStore.ts
- lib/stores/priorityQueueStore/PriorityQueueStore.ts
- lib/stores/priorityQueueStore/SqlServer/SqlServerPriorityQueueStore.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
- test/runtime/microservice/processes/domain/processTests.ts
- test/runtime/microservice/processes/domainEventDispatcher/processTests.ts
- test/unit/apis/awaitItem/ClientTests.ts
- test/unit/apis/awaitItem/httpTests.ts
The domain event dispatcher is the new connection piece between the domain servers and the flow servers. Although there is one more indirection in there.
So far the domain servers have published new domain events via the publisher server. The publisher server had only one channel for messages for a while but since #968 clients of the publisher server can send messages on specific channels and domain events have since then been sent (by default) via the `newDomainEvent` channel. These domain events were so far received by the domain server and the graphql server and published to outside clients.
The flow server must not only receive all newly published domain events live from the publisher server - it must also be able to receive replays of events, which are not meant for outside clients. …
> feat: Implement domain event dispatcher.

- lib/runtimes/singleProcess/processes/main/domain/fetchCommand.ts
This fixes the issue Dominique raised in the wolkenkit Slack, where the postgres priority queue store seemed broken.
The issue was not with the store implementation, but a problem that all persistent priority queues share: When retrieving an item from them, it's just an object and thus has to be converted to a CommandWithMetadata instance (or for whatever the priority queue is used). This was missing for commands in the single process runtime.
> fix: Convert item from priority queue to actual CommandWithMetadata.

- lib/common/application/getDomainDefinition.ts
- lib/common/application/getFlowsDefinition.ts
- lib/common/application/getHooksDefinition.ts
- lib/common/application/getInfrastructureDefinition.ts
- lib/common/application/getNotificationsDefinition.ts
- lib/common/application/getViewsDefinition.ts
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/SampleState.js
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/commands/authorize.js
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/domainEvents/authenticated.js
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/domainEvents/authorized.js
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/domainEvents/executed.js
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/domainEvents/succeeded.js
- test/shared/applications/javascript/withMissingModule/build/server/domain/sampleContext/sampleAggregate/index.js
- test/shared/applications/javascript/withMissingModule/build/server/flows/sampleFlow/handlers/sampleHandler.js
- test/shared/applications/javascript/withMissingModule/build/server/flows/sampleFlow/index.js
- test/shared/applications/javascript/withMissingModule/build/server/hooks/index.js
- test/shared/applications/javascript/withMissingModule/build/server/infrastructure/index.js
- test/shared/applications/javascript/withMissingModule/build/server/notifications/handlers/commandExecuteNotificationHandler.js
- test/shared/applications/javascript/withMissingModule/build/server/notifications/handlers/complexNotificationHandler.js
- test/shared/applications/javascript/withMissingModule/build/server/notifications/handlers/flowSampleFlowUpdatedNotificationHandler.js
- test/shared/applications/javascript/withMissingModule/build/server/notifications/handlers/viewSampleViewUpdatedNotificationHandler.js
- test/shared/applications/javascript/withMissingModule/build/server/notifications/index.js
- test/shared/applications/javascript/withMissingModule/build/server/views/sampleView/index.js
- test/shared/applications/javascript/withMissingModule/build/server/views/sampleView/notificationSubscribers/flowSampleFlowUpdatedNotificationSubscriber.js
- test/shared/applications/javascript/withMissingModule/build/server/views/sampleView/queries/all.js
- test/shared/applications/javascript/withMissingModule/package.json
- test/unit/common/application/loadApplicationTests.ts
This closes #1215.
I've decided to check whether the folders which are imported contain an `index.js` before attempting to import them.
Otherwise it would have been too complicated to differentiate between a `MODULE_NOT_FOUND` error thrown because of a missing `index.js` or because of a faulty import in the application.
> fix: Check application part existence and handle specific errors.

- lib/stores/priorityQueueStore/MySql/MySqlPriorityQueueStore.ts
- lib/stores/priorityQueueStore/Postgres/PostgresPriorityQueueStore.ts
- lib/stores/priorityQueueStore/SqlServer/SqlServerPriorityQueueStore.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
- Fixes an old and known bug that was fixed in mongodb and inmemory but still existed in mysql, postgres and mssql. Removing a queue from the priority queue did not check wether the queue to remove was the last in the priority queue and messed up the removal.
- Fixes a bug in the postgres implementation where the bulk update that moved the items in a queue one place to the front after acknowledging an item would cause a unique key constraint violation.
> fix: Fix priority queue acknowledge in multiple databases.

- lib/clis/wolkenkit/dev/devCommand.ts
- package.json
`PORT=4000 HEALTH_PORT=4001 yarn wolkenkit dev`
will output:
```
Starting the 'server' application...
API port     3000
Health port  3001
To stop the 'server' application, press <Ctrl>+<C>.
...
Health server started. (info)
Nil-mbp.local::undefined@undefined::wolkenkit@4.0.0-internal.88 (/Users/Nil/Workspace/jsnews/scrapeland/node_modules/wolkenkit/build/lib/runtimes/shared/runHealthServer.js)
16:59:51.910@2020-12-28 30744#1
{
healthPort: 4001
}
─────────────────────────────────
Single process runtime server started. (info)
Nil-mbp.local::undefined@undefined::wolkenkit@4.0.0-internal.88 (/Users/Nil/Workspace/jsnews/scrapeland/node_modules/wolkenkit/build/lib/runtimes/singleProcess/processes/main/app.js)
16:59:51.914@2020-12-28 30744#2
{
port: 4000
}
─────────────────────────────────
✗ …
```
> fix: dev command ports are inconsistent with env

- lib/stores/consumerProgressStore/MySql/MySqlConsumerProgressStore.ts
- lib/stores/domainEventStore/MySql/MySqlDomainEventStore.ts
- lib/stores/lockStore/MySql/MySqlLockStore.ts
- lib/stores/priorityQueueStore/MySql/MySqlPriorityQueueStore.ts
- lib/stores/utils/mySql/createPoolWithDefaults.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
@yeldiRium, @dotKuro and I noticed that our MariaDB stores couldn't handle emoji properly. We've determined that this is because, although the tables are configured properly, we forgot to set the connection to `utf8mb4` also. We've fixed this, added a regression test and also simplified our use of `createPool` by wrapping the method. This way, we can't forget to set the appropriate default options.
> fix: set utf8mb4 charset in MySQL connection options
