- lib/errors.js
- lib/wolkenkit/commands/start/index.js
- lib/wolkenkit/commands/start/verifyThatPortsAreAvailable.js
- package-lock.json
- package.json
I have added code to the `start` function to verify whether all requested ports are actually available, and to show a nice hint if not. For `stop` this is not needed, of course, and I also explicitly skipped it for `restart` and `reload`, because then the ports have been allocated before and should be available anyway.
Could you please have a look at what I did, and squash/merge it if you are fine with it?
> Verify that ports are available when starting an application.

- lib/bin/wolkenkit.js
- package-lock.json
- package.json
Hi @grundhoeferj!
I have added [update-notifier](https://github.com/yeoman/update-notifier) so that the CLI recognizes when new versions are available and tells the user to update.
Could you please review my changes, and squash / merge them if you are fine with them?
> Add update notifier.

- src/configuration/latest/core/container.js
Hi @mattwagl 😊 
As discussed, here's the small change in the CLI to support scaling in the core.
If you like, please squash/merge it 😊
> Set concurrency on commandbus for core. thenativeweb/org#682

- package.json
- src/wolkenkit/commands/init/cloneRepository.js
- src/wolkenkit/commands/shared/checkDocker.js
Improved information message for the prerequisites.
> Improved Information Message for CLI

- package-lock.json
- package.json
- src/wolkenkit/application/getConfiguration.js
- src/wolkenkit/commands/reload/index.js
- src/wolkenkit/commands/shared/validateCode.js
- src/wolkenkit/commands/start/index.js
This evening, I have rewritten the `wolkenkit-application` package, and introduced the required changes to the CLI, so that now we have a reliable code validation on `wolkenkit start` (and, we also get meaningful error messages if anything is missing or wrong).
Could you please review my changes, and squash / merge everything if you are fine with them?
> Add code validation on wolkenkit start. #132

- src/configuration/2.0.0/broker/container.js
- src/configuration/2.0.0/depot-file/container.js
- src/configuration/3.0.0/broker/container.js
- src/configuration/3.0.0/depot/container.js
- src/configuration/3.1.0/broker/container.js
- src/configuration/3.1.0/depot/container.js
- src/configuration/3.1.0/proxy/container.js
- src/configuration/latest/broker/container.js
- src/configuration/latest/depot/container.js
- src/configuration/latest/proxy/container.js
This PR changes the way we handle paths on Windows. If you are fine with that, please squash / merge it 😊
> Use POSIX paths for container internal paths. Closes #134

- package-lock.json
- package.json
- test/runtime/microservice/processes/dispatcher/processTests.js
Hi @yeldiRium 👋 
It's me again 😉 
I've removed another dependency, which was only used at a single place, and which could easily be replaced by a simple `while` loop. OTOH this leads to one less dependency.
Can you please review and squash / merge this?
> Replace small dependency.

- docker/wolkenkit-sqlserver/Dockerfile
Since the CTP's evaluation period was over, I updated the SQL Server base image.
As usual – can you please review, squash and merge?
> Update SQL Server.

- lib/common/data/PriorityQueue/FindPredicate.ts
- lib/common/data/PriorityQueue/PriorityQueue.ts
- test/unit/common/data/PriorityQueueTests.ts
Here comes the `find` function for our priority queue, including tests 😊 
Can you please review, squash and merge?
> Introduce find function.

- .github/CODEOWNERS
Hi @mattwagl 👋 
As discussed on Slack, I'm going to remove you from the current code owners file.
I agree that it is a good idea to re-add you for the websites / documentation stuff, but I would suggest to do this once we are going to merge that branch.
Could you please review, squash and merge this PR?
> Remove @mattwagl from global code owners.

- test/integration/stores/fileStore/getTestsFor.ts
- test/integration/stores/lockStore/getTestsFor.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
Hi @yeldiRium 👋 
The new roboter version has some stricter ESLint rules for Mocha, so I created this PR to fix that.
If you are fine with this, please squash / merge this 😊
> Fix ESLint warnings.

- lib/apis/awaitCommandWithMetadata/http/index.ts
- lib/apis/awaitCommandWithMetadata/http/v2/awaitCommandWithMetadata.ts
- lib/common/errors.ts
- lib/messaging/pubSub/InMemory/InMemoryPublisher.ts
- lib/messaging/pubSub/InMemory/InMemorySubscriber.ts
- lib/messaging/pubSub/createPublisher.ts
- lib/messaging/pubSub/createSubscriber.ts
- lib/runtimes/microservice/processes/dispatcher/Configuration.ts
- lib/runtimes/microservice/processes/dispatcher/app.ts
- lib/runtimes/microservice/processes/dispatcher/getApi.ts
- lib/runtimes/microservice/processes/dispatcher/getConfiguration.ts
- lib/runtimes/microservice/processes/dispatcher/getOnReceiveCommand.ts
- test/integration/messaging/pubSub/InMemoryTests.ts
- test/unit/apis/awaitCommandWithMetadata/httpTests.ts
Hi @goloroden,
I've integrated the PubSub mechanism from #370 into the dispatcher process as described in #369. I've made some minor changes to the PubSub implementation while integrating it.
Please take a look and merge, if you're fine with it.
> feat: Integrate PubSub mechanism into dispatcher process.

- templates/chat-simplified/typescript/server/domain/communication/message.ts
- test/cli/buildTests.ts
- test/shared/applications/javascript/base-uncompiled/server/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withAggregateEnhancer/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withDomainEventAuthorization/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withDomainEventFilter/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withDomainEventMap/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withEmptyAggregateDirectory/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withEmptyViewDirectory/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withInvalidAggregate/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withInvalidView/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withSyntaxError/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withViewEnhancer/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withoutViewsDirectory/build/domain/sampleContext/sampleAggregate/commands/execute.js
- test/unit/common/application/buildApplicationTests.ts
> fix: Clean up test and example applications.

- lib/clis/wolkenkit/build/buildCommand.ts
- lib/clis/wolkenkit/createDeployment/createDeploymentCommand.ts
- lib/clis/wolkenkit/dev/devCommand.ts
- lib/clis/wolkenkit/documentation/documentationCommand.ts
- test/cli/createDeploymentTests.ts
> chore: Streamline CLI messages.

- test/unit/apis/graphql/graphqlTests.ts
- test/unit/apis/observeDomainEvents/httpTests.ts
- test/unit/common/application/getApplicationDefinitionTests.ts
> chore: Test rejected events recipients

- lib/apis/awaitCommandWithMetadata/http/v2/acknowledge.ts
- lib/apis/awaitCommandWithMetadata/http/v2/awaitCommandWithMetadata.ts
- lib/apis/awaitCommandWithMetadata/http/v2/renewLock.ts
- lib/runtimes/microservice/processes/dispatcher/getOnReceiveCommand.ts
- lib/runtimes/microservice/processes/graphql/app.ts
- lib/runtimes/singleProcess/processes/main/acknowledgeCommand.ts
- lib/runtimes/singleProcess/processes/main/app.ts
- lib/runtimes/singleProcess/processes/main/keepRenewingLock.ts
- lib/stores/priorityQueueStore/InMemory/InMemoryPriorityQueueStore.ts
- lib/stores/priorityQueueStore/InMemory/Queue.ts
- lib/stores/priorityQueueStore/PriorityQueueStore.ts
- lib/stores/priorityQueueStore/createPriorityQueueStore.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
- test/unit/apis/awaitCommandWithMetadata/ClientTests.ts
- test/unit/apis/awaitCommandWithMetadata/httpTests.ts
> feat: Allow setting an external discriminator for the priority queue.

- lib/apis/awaitCommandWithMetadata/http/v2/Client.ts
- lib/apis/awaitCommandWithMetadata/http/v2/defer.ts
- lib/apis/awaitCommandWithMetadata/http/v2/index.ts
- lib/stores/priorityQueueStore/InMemory/InMemoryPriorityQueueStore.ts
- lib/stores/priorityQueueStore/PriorityQueueStore.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
- test/unit/apis/awaitCommandWithMetadata/ClientTests.ts
- test/unit/apis/awaitCommandWithMetadata/httpTests.ts
> feat: Allow clients to defer items from queue.

- lib/stores/domainEventStore/MongoDb/MongoDbDomainEventStore.ts
- lib/stores/lockStore/MongoDb/MongoDbLockStore.ts
Fixes #362.
Support transactions for the domain event store and the lock store.
> Support MongoDb transactions

- lib/clis/wolkenkit/createDeployment/dockerCompose/getMicroserviceInMemoryManifest.ts
- lib/clis/wolkenkit/createDeployment/dockerCompose/getMicroservicePostgresManifest.ts
- lib/clis/wolkenkit/createDeployment/dockerCompose/getSingleProcessInMemoryManifest.ts
- lib/clis/wolkenkit/createDeployment/dockerCompose/getSingleProcessPostgresManifest.ts
> feat: Enable production mode in Dockerfiles.

- .github/workflows/qa.yml
- lib/stores/priorityQueueStore/InMemory/InMemoryPriorityQueueStore.ts
- lib/stores/priorityQueueStore/MySql/MySqlPriorityQueueStore.ts
- lib/stores/priorityQueueStore/MySql/Queue.ts
- lib/stores/priorityQueueStore/MySql/TableNames.ts
- lib/stores/priorityQueueStore/MySql/index.ts
- lib/stores/priorityQueueStore/common/getIndexOfLeftChild.ts
- lib/stores/priorityQueueStore/common/getIndexOfParent.ts
- lib/stores/priorityQueueStore/common/getIndexOfRightChild.ts
- lib/stores/priorityQueueStore/createPriorityQueueStore.ts
- lib/stores/utils/mySql/withTransaction.ts
- test/integration/stores/priorityQueueStore/InMemoryTests.ts
- test/integration/stores/priorityQueueStore/MySqlTests.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
> feat: Add PriorityQueueStore implementation for MySql databases.

- lib/clis/wolkenkit/createDeployment/dockerCompose/getMicroservicePostgresManifest.ts
- lib/clis/wolkenkit/createDeployment/dockerCompose/getSingleProcessPostgresManifest.ts
- lib/runtimes/singleProcess/processes/main/Configuration.ts
- lib/runtimes/singleProcess/processes/main/app.ts
- lib/runtimes/singleProcess/processes/main/getConfiguration.ts
- lib/stores/domainEventStore/Postgres/PostgresDomainEventStore.ts
- lib/stores/priorityQueueStore/MySql/MySqlPriorityQueueStore.ts
- lib/stores/priorityQueueStore/Postgres/PostgresPriorityQueueStore.ts
- lib/stores/priorityQueueStore/Postgres/Queue.ts
- lib/stores/priorityQueueStore/Postgres/TableNames.ts
- lib/stores/priorityQueueStore/Postgres/index.ts
- lib/stores/priorityQueueStore/createPriorityQueueStore.ts
- lib/stores/utils/postgres/withTransaction.ts
- test/integration/stores/priorityQueueStore/PostgresTests.ts
Also clean up MySQL PriorityQueueStore implementation and PostgreSQL
DomainEventStore implementation a bit.
Part of #851.
> feat: Add PriorityQueueStore implementation for PostgreSQL.

- lib/common/application/compileWithTypeScript.ts
> fix: Fix dev command on Windows.

- lib/apis/graphql/OnCancelCommand.ts
- lib/apis/graphql/index.ts
- lib/apis/graphql/v2/handleCommand/getCancelResolver.ts
- lib/apis/graphql/v2/handleCommand/getMutationResolvers.ts
- lib/apis/graphql/v2/handleCommand/getTypeDefinitions.ts
- lib/apis/graphql/v2/index.ts
- lib/runtimes/microservice/processes/graphql/app.ts
- lib/runtimes/microservice/processes/graphql/getApi.ts
- lib/runtimes/singleProcess/processes/main/getApi.ts
- test/runtime/microservice/processes/graphql/processTests.ts
- test/runtime/singleProcess/processes/main/processTests.ts
- test/unit/apis/graphql/graphqlTests.ts
> feat: Implement command cancellation in graphql API.

- lib/common/application/InfrastructureDefinition.ts
- lib/common/application/loadApplication.ts
I don't see a good way to tests this. @goloroden do you maybe have an idea?
Closes #1122.
> feat: Pass logger service to setupInfrastructure and getInfrastructure.

- lib/common/elements/User.ts
- lib/common/utils/mapKeysDeep.ts
- lib/stores/domainEventStore/MongoDb/MongoDbDomainEventStore.ts
- lib/stores/priorityQueueStore/MongoDb/MongoDbPriorityQueueStore.ts
- lib/stores/utils/mongoDb/escapeFieldNames.ts
- test/integration/stores/domainEventStore/getTestsFor.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
- test/unit/common/utils/mapKeysDeepTests.ts
- test/unit/stores/utils/mongoDb/escapeFieldNamesTests.ts
- test/unit/stores/utils/mongoDb/unescapeFieldNamesTests.ts
> feat: Escape customizable field names in mongodb stores.

- lib/stores/priorityQueueStore/InMemory/InMemoryPriorityQueueStore.ts
- test/integration/stores/priorityQueueStore/getTestsFor.ts
> fix: Fix index maintenance in InMemory PriorityQueueStore.

- lib/stores/fileStore/FileSystem/FileSystemFileStore.ts
- lib/stores/fileStore/FileSystem/FileSystemFileStoreOptions.ts
- test/integration/stores/fileStore/FileSystemTests.ts
> fix: Make directory non-optional for filesystem file store.

- README.md
- lib/apis/graphql/v2/handleCommand/getAggregateFieldConfiguration.ts
- lib/apis/graphql/v2/handleCommand/getCommandFieldConfiguration.ts
- lib/apis/handleCommand/http/getApiDefinitions.ts
- lib/apis/handleCommand/http/v2/Client.ts
- lib/apis/handleCommand/http/v2/index.ts
- lib/apis/handleCommand/http/v2/postCommand.ts
- lib/apis/handleCommand/http/v2/postCommandWithoutAggregateId.ts
- package-lock.json
- package.json
- test/unit/apis/graphql/graphqlTests.ts
- test/unit/apis/handleCommand/ClientTests.ts
- test/unit/apis/handleCommand/httpTests.ts
> feat: Make aggregate id optional in command accepting APIs.

- lib/apis/graphql/v2/index.ts
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/SampleState.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/commands/authenticate.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/commands/authorize.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/commands/execute.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/domainEvents/authenticated.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/domainEvents/authorized.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/domainEvents/executed.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/domainEvents/succeeded.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/domain/sampleContext/sampleAggregate/index.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/flows/sampleFlow/handlers/sampleHandler.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/flows/sampleFlow/index.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/hooks/index.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/infrastructure/index.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/views/sampleView/index.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/build/server/views/sampleView/queries/all.js
- test/shared/applications/javascript/withInvalidGraphQlSchema/package.json
- test/unit/apis/graphql/graphqlTests.ts
> feat: Validate GraphQL Schema on startup and abort if it is invalid.

- lib/common/utils/test/sandbox/CommandForAggregateSandbox.ts
- lib/common/utils/test/sandbox/DomainEventForAggregateSandbox.ts
- lib/common/utils/test/sandbox/DomainEventForFlowSandbox.ts
- lib/common/utils/test/sandbox/SandboxForAggregate.ts
- lib/common/utils/test/sandbox/SandboxForFlow.ts
- lib/common/utils/test/sandbox/createSandboxForAggregate.ts
- lib/common/utils/test/sandbox/createSandboxForFlow.ts
- lib/wolkenkit.ts
> feat: Provide types for sandbox parameters.

- lib/apis/base/getApiBase.ts
- package-lock.json
- package.json
> feat: Add helmet to base API.

- lib/apis/graphql/v2/index.ts
- test/unit/apis/graphql/graphqlTests.ts
> fix: Respect CORS configuration in GraphQL API.
